### ISSUE TITLE
Comment on Metrics included in Plutocracy.py (Metrics discussion)

### ISSUE THREAD

**Issue by AngelaKTE** [TE-Academy/Reputation-based_Weighted_Voting#50]
#### Description

Below some comments to finalize the selection of metrics to be included in \`plutocracy.py\`

* I went over Vitalik’s criticism on Gini. [https://vitalik.eth.limo/general/2021/07/29/gini.html](https://vitalik.eth.limo/general/2021/07/29/gini.html)
* I get his comments, however I think this does not apply to voting weights well.
* I think it's valuable to provide all metrics you prepared

For the write-up, I'd like to

* put the focus on two metrics: a) Gini Coefficient (with Lorenz Curve plot) b) HH Index with plotting the square chart …and run the analysis with the example of the TE Academy NFT distribution in the voting, see issue #TE-64

Plus we provide Theil L+T in the `plutocracy.py`notebook and if you think valuable, refer to Vitalik’s post.

**Comment by eightarmsninebrains** [comment]
I think it's important to keep all of the metrics. I'd like to know more about why we shift away from the metrics that were actually used in TE Academy fellowship selection voting. 

My thought would be: if we are going more general with new metrics, we generate new data. If we are using TE Academy data, we stick closer to the metrics that were actually used in the process. There is a reason, for instance, that Gini Coefficient was specifically not used as a TE Academy fellowship metric, since it tends to lead to emotional narratives around "fairness" that were  not matched to the TE Academy concerns surrounding expertise having sufficient influence.
